version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    ports:
      - 80:8080
    restart: always
    tty: true
    volumes:
      - ./app/my-vue-app:/app
    
  backend:
    container_name: backend
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8004:8000
    restart: always
    tty: true
    volumes:
      - ./app/python:/app
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data:
